name: Awesome readme to data
description: A GitHub Action that transform awesome readme to data and commit in PR 
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: database
  color: green