name: Awesome readme to data
description: A GitHub Action that transform awesome readme to data and commit in PR 
inputs:
  entry: 
    description: Entry file for parsing
    default: './README.md'
  output: 
    description: Output file for save data
    default: './data/dataset.json'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: database
  color: green